{"name": "Проверка , если авторизоваться под несуществующим пользователем, запрос возвращает ошибку", "status": "passed", "description": "Проверяем ,что при отсутствии логина,возвращается ошибка и сообщение об ошибке 'Учетная запись не найдена'", "steps": [{"name": "Авторизация курьера с неправильными данными", "status": "passed", "start": 1715505702112, "stop": 1715505703298}], "start": 1715505702112, "stop": 1715505703300, "uuid": "aed66866-5f4f-410c-85ee-cc6cb77de149", "historyId": "19cd49565c5ca54056381484040483f5", "testCaseId": "19cd49565c5ca54056381484040483f5", "fullName": "tests.py.test_login_courier.TestLoginCourier#test_invalid_login", "labels": [{"name": "parentSuite", "value": "tests.py"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-AQPR8BL"}, {"name": "thread", "value": "24924-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.py.test_login_courier"}]}