{"name": "Проверка , если авторизоваться под несуществующим пользователем, запрос возвращает ошибку", "status": "passed", "description": "Проверяем ,что при отсутствии логина,возвращается ошибка и сообщение об ошибке 'Учетная запись не найдена'", "steps": [{"name": "Авторизация курьера с неправильными данными", "status": "passed", "start": 1715634405701, "stop": 1715634406184}], "start": 1715634405701, "stop": 1715634406187, "uuid": "7d362f81-62ef-4e4e-8c76-61aa59db270b", "historyId": "19cd49565c5ca54056381484040483f5", "testCaseId": "19cd49565c5ca54056381484040483f5", "fullName": "tests.py.test_login_courier.TestLoginCourier#test_invalid_login", "labels": [{"name": "parentSuite", "value": "tests.py"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-AQPR8BL"}, {"name": "thread", "value": "21720-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.py.test_login_courier"}]}